import { resolveOrchestrationSessionConfiguration, type OrchestrationViteEnvironment } from "./orchestration-session.js";
import "./multi-paper-runtime-center.css";

type Mode = "simulation" | "live";
type Tab = "performance" | "trace" | "trades" | "configuration" | "promotion";
type Account = { cash?: number; equity?: number; realizedPnl?: number; unrealizedPnl?: number; fees?: number; positions?: unknown[] };
type Cycle = { cycleId?: string; traceId?: string; status?: string; startedAt?: string; executionMode?: string; decision?: unknown[]; portfolio?: { selectedCount?: number }; risk?: unknown[]; execution?: unknown[]; account?: Account };
type Deployment = { definition: { deploymentId: string; name: string; strategyVersionId: string; accountId: string; initialCapital: number; datasetFingerprint: string; graphFingerprint: string; executionFingerprint: string; riskFingerprint: string; runtimeApplied: false; exchangeWriteAllowed: false }; state: { lifecycle: string; latestCycle: number; latestRunId?: string; heartbeatAt?: string; retryAt?: string; health: string; failureCount: number; sourceFingerprint: string } };
type Projection = Record<string, unknown>;
type ApiPage = { data: Projection[]; nextCursor?: string };

const env: OrchestrationViteEnvironment = { DEV: import.meta.env.DEV, VITE_TRADEBOT_ORCHESTRATION_API: import.meta.env.VITE_TRADEBOT_ORCHESTRATION_API, VITE_TRADEBOT_ORCHESTRATION_TOKEN: import.meta.env.DEV ? import.meta.env.VITE_TRADEBOT_ORCHESTRATION_TOKEN : undefined };
const globals = globalThis as typeof globalThis & { __TRADEBOT_ORCHESTRATION_API__?: string; __TRADEBOT_ORCHESTRATION_TOKEN__?: string };
const session = resolveOrchestrationSessionConfiguration({ globalApiBase: globals.__TRADEBOT_ORCHESTRATION_API__, globalToken: globals.__TRADEBOT_ORCHESTRATION_TOKEN__, viteEnvironment: env });
const selectedStorageKey = "tradebot.multi-paper.selected";
let mode: Mode = "simulation", deployments: Deployment[] = [], selectedId = readSelected(), tab: Tab = "performance", listRequest: AbortController | undefined, detailRequest: AbortController | undefined, epoch = 0, error = "", refreshTimer: number | undefined;
const cyclesByDeployment = new Map<string, Cycle[]>();
const detailByKey = new Map<string, Projection[]>();
const root = () => document.querySelector<HTMLElement>("#multi-paper-runtime-center-host");
const esc = (v: unknown) => String(v ?? "—").replace(/[&<>"']/gu, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const idempotency = () => `web-paper-${crypto.randomUUID()}`;
const t = (zh: string, en: string) => document.documentElement.lang === "zh-CN" ? zh : en;
function readSelected(): string | undefined { try { return localStorage.getItem(selectedStorageKey) ?? undefined; } catch { return undefined; } }
function saveSelected(id: string | undefined): void { try { if (id) localStorage.setItem(selectedStorageKey, id); else localStorage.removeItem(selectedStorageKey); } catch { /* Selection remains in memory when storage is unavailable. */ } }
async function api(path: string, signal: AbortSignal, body?: unknown): Promise<any> { const response = await fetch(`${session.apiBase}${path}`, { method: body === undefined ? "GET" : "POST", headers: { authorization: `Bearer ${session.token}`, ...(body === undefined ? {} : { "content-type": "application/json" }) }, body: body === undefined ? undefined : JSON.stringify(body), signal }); const value = await response.json(); if (!response.ok) throw new Error(value.error?.code ?? `HTTP_${response.status}`); return value; }
const latestCycle = (deployment: Deployment): Cycle | undefined => cyclesByDeployment.get(deployment.definition.deploymentId)?.[0];
const money = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : "unavailable";
function metric(deployment: Deployment, label: string, value: string): string { return `<div class="paper-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`; }
function actionDisabled(d: Deployment, action: string): boolean { return action === "preflight" ? !["draft", "stopped", "failed"].includes(d.state.lifecycle) : action === "start" ? d.state.lifecycle !== "preflight_passed" : action === "stop" ? !["running", "stopping", "close_only"].includes(d.state.lifecycle) : d.state.lifecycle !== "stopped"; }
function svgCurve(deploymentsToDraw: readonly Deployment[]): string {
  const lines = deploymentsToDraw.flatMap((deployment, index) => {
    const facts = [...(cyclesByDeployment.get(deployment.definition.deploymentId) ?? [])].reverse().filter((item) => typeof item.account?.equity === "number");
    if (facts.length < 2) return [];
    const values = facts.map(item => item.account!.equity!); const minimum = Math.min(...values), maximum = Math.max(...values); const span = maximum - minimum || 1;
    const points = values.map((value, point) => `${(point / Math.max(1, values.length - 1)) * 100},${54 - ((value - minimum) / span) * 46}`).join(" ");
    return [`<polyline class="paper-curve paper-curve-${index % 5}" points="${points}" aria-label="${esc(deployment.definition.name)}"/>`];
  });
  return lines.length ? `<svg class="paper-chart" viewBox="0 0 100 60" preserveAspectRatio="none" role="img" aria-label="${t("独立模拟收益曲线", "Independent simulation equity curves")}"><line x1="0" y1="54" x2="100" y2="54" class="paper-axis"/>${lines.join("")}</svg>` : `<p class="paper-unavailable">${t("尚无足够的持久周期事实，无法绘制曲线。", "Insufficient persisted cycle facts for a curve.")}</p>`;
}
function overview(deployment: Deployment): string { const cycle = latestCycle(deployment); const account = cycle?.account; const equity = account?.equity; const returnPct = typeof equity === "number" ? ((equity - deployment.definition.initialCapital) / deployment.definition.initialCapital) * 100 : undefined; return `<article class="paper-overview-card"><header><strong>${esc(deployment.definition.name)}</strong><code>${esc(deployment.state.lifecycle)}</code></header><div class="paper-metrics">${metric(deployment, "Equity", money(equity))}${metric(deployment, "Return", returnPct === undefined ? "unavailable" : `${returnPct.toFixed(3)}%`)}${metric(deployment, t("周期", "Cycles"), String(deployment.state.latestCycle))}${metric(deployment, t("健康", "Health"), deployment.state.health)}</div><small>${t("心跳", "Heartbeat")}: ${esc(deployment.state.heartbeatAt ?? "unavailable")} · ${t("账户", "Account")}: ${esc(deployment.definition.accountId)}</small></article>`; }
function render(): void {
  const host = root(); if (!host) return;
  const selected = deployments.find(d => d.definition.deploymentId === selectedId) ?? deployments[0]; if (selected && selectedId !== selected.definition.deploymentId) { selectedId = selected.definition.deploymentId; saveSelected(selectedId); }
  host.innerHTML = `<section class="multi-paper-center"><header><div><p class="eyebrow">Paper Only · runtimeApplied=false · exchangeWriteAllowed=false</p><h2>${t("多模拟运行中心", "Simulation runtime center")}</h2><p>${t("每个实例拥有独立账户、持仓、订单、成交、轨迹与 Artifact。视图切换没有运行时副作用。", "Each instance has its own account, positions, orders, fills, traces, and artefacts. Changing view has no runtime side effect.")}</p></div><div class="simulation-switch" role="group" aria-label="${t("运行视图", "Runtime view")}"><button data-paper-mode="simulation" aria-pressed="${mode === "simulation"}">${t("模拟", "Simulation")}</button><button data-paper-mode="live" aria-pressed="${mode === "live"}">${t("真实", "Live")}</button></div></header>${mode === "live" ? `<div class="paper-live-unavailable"><strong>Live unavailable</strong><span>Paper Only · Exchange writes OFF</span><p>${t("此视图只说明安全边界；不会启动、暂停、停止或替换模拟实例。", "This view only explains the safety boundary; it never starts, pauses, stops, or replaces simulations.")}</p></div>` : simulationMarkup(selected)}</section>`;
}
function simulationMarkup(selected: Deployment | undefined): string {
  const cards = deployments.map(overview).join("") || `<p class="paper-empty">${t("尚无模拟实例。请使用已验证的 Strategy Version 创建草案。", "No simulations yet. Create a draft with a server-validated Strategy Version.")}</p>`;
  const rows = deployments.map(d => `<button class="paper-deployment ${d.definition.deploymentId === selected?.definition.deploymentId ? "is-selected" : ""}" data-paper-select="${esc(d.definition.deploymentId)}"><strong>${esc(d.definition.name)}</strong><code>${esc(d.state.lifecycle)} · ${esc(d.state.health)}</code><small>${esc(d.definition.strategyVersionId)} · ${d.state.latestCycle} ${t("周期", "cycles")}</small></button>`).join("");
  const tabs: Array<[Tab,string,string]> = [["performance","表现","Performance"],["trace","Agent 轨迹","Agent trace"],["trades","交易","Trades"],["configuration","配置与数据","Configuration & data"],["promotion","晋升评估","Promotion assessment"]];
  return `<div class="paper-overview"><section><h3>Simulation Overview</h3><p>${t("指标和曲线仅从持久账户、周期与成交事实计算。", "Metrics and curves are calculated only from persisted account, cycle, and fill facts.")}</p><div class="paper-curve-wrap">${svgCurve(deployments.slice(0, 5))}</div><div class="paper-overview-cards">${cards}</div><form data-paper-create><label>${t("名称", "Name")}<input name="name" required maxlength="80"></label><label>Strategy Version<input name="strategyVersionId" required pattern="[a-z0-9._:-]+" aria-describedby="paper-strategy-help"></label><label>${t("初始资金", "Initial capital")}<input name="initialCapital" type="number" min="1" value="10000" required></label><label>${t("周期（毫秒）", "Interval (ms)")}<input name="intervalMs" type="number" min="1000" value="60000" required></label><small id="paper-strategy-help">${t("仅接受服务端已有且可物化的不可变版本。", "Only an existing, server-materializable immutable version is accepted.")}</small><button>${t("创建模拟草案", "Create simulation draft")}</button></form>${error ? `<p class="paper-error" role="alert">${esc(error)}</p>` : ""}</section><aside class="paper-deployment-list" aria-label="${t("模拟实例", "Simulation instances")}">${rows}</aside></div>${selected ? `<section class="paper-detail"><header><div><h3>${esc(selected.definition.name)}</h3><code>${esc(selected.definition.deploymentId)}</code></div><div class="paper-actions">${["preflight", "start", "stop", "archive"].map(action => `<button data-paper-action="${action}" ${actionDisabled(selected, action) ? "disabled" : ""}>${esc(action[0]!.toUpperCase() + action.slice(1))}</button>`).join("")}</div></header><p class="paper-runtime-state">${t("状态", "State")}: <strong>${esc(selected.state.lifecycle)}</strong>${selected.state.retryAt ? ` · ${t("下次重试", "Next retry")}: ${esc(selected.state.retryAt)}` : ""}</p><nav aria-label="${t("实例详情", "Instance detail")}">${tabs.map(([id, zh, en]) => `<button data-paper-tab="${id}" aria-pressed="${tab === id}">${t(zh, en)}</button>`).join("")}</nav><div class="paper-detail-content">${detail(selected)}</div></section>` : ""}`;
}
function dataFor(deployment: Deployment, kind: string): Projection[] { return detailByKey.get(`${deployment.definition.deploymentId}:${kind}`) ?? []; }
function pretty(value: unknown): string { return `<pre>${esc(JSON.stringify(value, null, 2))}</pre>`; }
function strings(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function traceLineage(fact: Projection): string {
  const artifacts = Array.isArray(fact.artifacts) ? fact.artifacts as Projection[] : [];
  const trace = Array.isArray(fact.trace) ? fact.trace as Projection[] : [];
  const artifactRows = artifacts.map(artifact => `<li><code>${esc(artifact.stage)}</code> · ${esc(artifact.agent)} · ${esc(artifact.status)}${artifact.symbol ? ` · ${esc(artifact.symbol)}` : ""}<small>${esc(artifact.artifactId)}${strings(artifact.sourceArtifactIds).length ? ` ← ${strings(artifact.sourceArtifactIds).map(esc).join(", ")}` : ""}</small></li>`).join("");
  const stages = trace.map(event => `${String(event.stage ?? "?")}:${String(event.phase ?? "?")}`).join(" → ");
  return `<article class="paper-fact paper-lineage"><h4>${esc(fact.cycleId ?? fact.traceId)}</h4><p>${t("Decision → Portfolio → Risk → Execution", "Decision → Portfolio → Risk → Execution")}</p><small>${esc(stages || t("尚无阶段事件", "No stage events recorded"))}</small><ol>${artifactRows || `<li>${t("尚无 Artifact", "No artifacts recorded")}</li>`}</ol></article>`;
}
function detail(deployment: Deployment): string {
  const cycles = cyclesByDeployment.get(deployment.definition.deploymentId) ?? [];
  if (tab === "performance") { const latest = cycles[0]; return latest ? `<div class="paper-detail-grid">${metric(deployment, "Equity", money(latest.account?.equity))}${metric(deployment, t("已实现盈亏", "Realized PnL"), money(latest.account?.realizedPnl))}${metric(deployment, t("费用", "Fees"), money(latest.account?.fees))}${metric(deployment, t("最新周期", "Latest cycle"), esc(latest.cycleId))}</div>${pretty({ status: latest.status, account: latest.account })}` : `<p class="paper-unavailable">${t("暂无账户或周期事实。", "No account or cycle facts yet.")}</p>`; }
  if (tab === "trace") { const facts = dataFor(deployment, "artifacts"); return facts.length ? facts.map(traceLineage).join("") : `<p class="paper-unavailable">${t("正在按需读取 Agent 轨迹与 Artifact lineage。", "Agent trace and artifact lineage are loaded on demand.")}</p>`; }
  if (tab === "trades") { const facts = dataFor(deployment, "trades"); return facts.length ? `<div class="paper-facts">${facts.map(fact => `<article class="paper-fact"><strong>${esc(fact.kind)}</strong>${pretty(fact.execution ?? fact.risk ?? fact)}</article>`).join("")}</div>` : `<p class="paper-unavailable">${t("暂无 order、fill、position、fee 或 risk rejection 事实。", "No order, fill, position, fee, or risk-rejection facts yet.")}</p>`; }
  if (tab === "configuration") return `<dl class="paper-config"><div><dt>Strategy Version</dt><dd>${esc(deployment.definition.strategyVersionId)}</dd></div><div><dt>Dataset</dt><dd>${esc(deployment.definition.datasetFingerprint)}</dd></div><div><dt>Graph</dt><dd>${esc(deployment.definition.graphFingerprint)}</dd></div><div><dt>Execution</dt><dd>${esc(deployment.definition.executionFingerprint)}</dd></div><div><dt>Risk</dt><dd>${esc(deployment.definition.riskFingerprint)}</dd></div><div><dt>Source</dt><dd>${esc(deployment.state.sourceFingerprint)}</dd></div><div><dt>Safety</dt><dd>Paper Only · runtimeApplied=false · exchangeWriteAllowed=false</dd></div></dl>`;
  return `<p>${t("只读评估：", "Read-only assessment:")} ${cycles.length < 5 ? t("数据不足；继续观察。", "insufficient data; continue observing.") : t("可提交后续验证。", "ready to submit for a later validation.")} ${t("不会自动部署、替换 Champion 或应用 Runtime。", "It never auto-deploys, replaces a Champion, or applies Runtime.")}</p>`;
}
async function loadCycles(signal: AbortSignal, stamp: number): Promise<void> { const selected = deployments.slice(0, 5); await Promise.all(selected.map(async deployment => { const value = await api(`/api/orchestration/paper-deployments/${encodeURIComponent(deployment.definition.deploymentId)}/cycles?limit=300`, signal) as ApiPage; if (!signal.aborted && stamp === epoch) cyclesByDeployment.set(deployment.definition.deploymentId, value.data as Cycle[]); })); }
async function load(): Promise<void> { listRequest?.abort(); const controller = listRequest = new AbortController(), stamp = ++epoch; try { const result = await api("/api/orchestration/paper-deployments?limit=50", controller.signal); if (controller.signal.aborted || stamp !== epoch) return; deployments = result.data; await loadCycles(controller.signal, stamp); if (controller.signal.aborted || stamp !== epoch) return; error = ""; } catch (cause) { if (!controller.signal.aborted && stamp === epoch) error = cause instanceof Error ? cause.message : "REQUEST_FAILED"; } render(); }
async function loadDetail(deployment: Deployment, kind: "runs" | "cycles" | "trades" | "artifacts"): Promise<void> { detailRequest?.abort(); const controller = detailRequest = new AbortController(), stamp = ++epoch; const limit = kind === "artifacts" ? 12 : 50; try { const result = await api(`/api/orchestration/paper-deployments/${encodeURIComponent(deployment.definition.deploymentId)}/${kind}?limit=${limit}`, controller.signal) as ApiPage; if (!controller.signal.aborted && stamp === epoch) { detailByKey.set(`${deployment.definition.deploymentId}:${kind}`, result.data); render(); } } catch (cause) { if (!controller.signal.aborted && stamp === epoch) { error = cause instanceof Error ? cause.message : "DETAIL_REQUEST_FAILED"; render(); } } }
async function action(name: "preflight" | "start" | "stop" | "archive"): Promise<void> { const selected = deployments.find(d => d.definition.deploymentId === selectedId); if (!selected || actionDisabled(selected, name)) return; const controller = listRequest = new AbortController(), stamp = ++epoch; try { await api(`/api/orchestration/paper-deployments/${encodeURIComponent(selected.definition.deploymentId)}/${name}`, controller.signal, { idempotencyKey: idempotency(), sourceFingerprint: selected.state.sourceFingerprint }); if (stamp === epoch) await load(); } catch (cause) { if (!controller.signal.aborted && stamp === epoch) { error = cause instanceof Error ? cause.message : "ACTION_FAILED"; render(); } } }
function startRefresh(): void { if (refreshTimer !== undefined) return; refreshTimer = window.setInterval(() => { if (root() && mode === "simulation" && deployments.some(deployment => ["running", "stopping", "close_only"].includes(deployment.state.lifecycle))) void load(); }, 5_000); }
function stopRefresh(): void { if (refreshTimer !== undefined) window.clearInterval(refreshTimer); refreshTimer = undefined; }
document.addEventListener("click", event => { const host = root(), target = (event.target as HTMLElement).closest<HTMLElement>("[data-paper-mode],[data-paper-select],[data-paper-action],[data-paper-tab]"); if (!host || !target || !host.contains(target)) return; if (target.dataset.paperMode) { mode = target.dataset.paperMode as Mode; render(); return; } if (target.dataset.paperSelect) { detailRequest?.abort(); selectedId = target.dataset.paperSelect; saveSelected(selectedId); tab = "performance"; render(); return; } if (target.dataset.paperTab) { tab = target.dataset.paperTab as Tab; const deployment = deployments.find(item => item.definition.deploymentId === selectedId); render(); if (deployment && (tab === "trace" || tab === "trades")) void loadDetail(deployment, tab === "trace" ? "artifacts" : "trades"); return; } if (target.dataset.paperAction) void action(target.dataset.paperAction as "preflight" | "start" | "stop" | "archive"); });
document.addEventListener("submit", event => { const form = event.target as HTMLFormElement; if (!form.matches("[data-paper-create]")) return; event.preventDefault(); const controller = listRequest = new AbortController(); const values = new FormData(form); void api("/api/orchestration/paper-deployments", controller.signal, { idempotencyKey:idempotency(), name:String(values.get("name")), strategyVersionId:String(values.get("strategyVersionId")), initialCapital:Number(values.get("initialCapital")), intervalMs:Number(values.get("intervalMs")) }).then(load).catch(cause=>{ if (!controller.signal.aborted) { error=cause instanceof Error?cause.message:"CREATE_FAILED"; render(); } }); });
window.addEventListener("tradebot:multi-paper-remount", () => { if (root()) { startRefresh(); void load(); } else { listRequest?.abort(); detailRequest?.abort(); stopRefresh(); } });
if (root()) { startRefresh(); void load(); }
