import { resolveOrchestrationSessionConfiguration, type OrchestrationViteEnvironment } from "./orchestration-session.js";
import "./multi-paper-runtime-center.css";

type Mode = "simulation" | "live";
type Tab = "performance" | "trace" | "trades" | "configuration" | "promotion";
type Deployment = { definition: { deploymentId: string; name: string; strategyVersionId: string; initialCapital: number; runtimeApplied: false; exchangeWriteAllowed: false }; state: { lifecycle: string; latestCycle: number; heartbeatAt?: string; health: string; sourceFingerprint: string } };
const env: OrchestrationViteEnvironment = { DEV: import.meta.env.DEV, VITE_TRADEBOT_ORCHESTRATION_API: import.meta.env.VITE_TRADEBOT_ORCHESTRATION_API, VITE_TRADEBOT_ORCHESTRATION_TOKEN: import.meta.env.DEV ? import.meta.env.VITE_TRADEBOT_ORCHESTRATION_TOKEN : undefined };
const globals = globalThis as typeof globalThis & { __TRADEBOT_ORCHESTRATION_API__?: string; __TRADEBOT_ORCHESTRATION_TOKEN__?: string };
const session = resolveOrchestrationSessionConfiguration({ globalApiBase: globals.__TRADEBOT_ORCHESTRATION_API__, globalToken: globals.__TRADEBOT_ORCHESTRATION_TOKEN__, viteEnvironment: env });
let mode: Mode = "simulation", deployments: Deployment[] = [], selectedId: string | undefined, tab: Tab = "performance", request: AbortController | undefined, epoch = 0, error = "", loaded = new Set<string>();
const root = () => document.querySelector<HTMLElement>("#multi-paper-runtime-center-host");
const esc = (v: string) => v.replace(/[&<>"']/gu, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const idempotency = () => `web-paper-${crypto.randomUUID()}`;
async function api(path: string, signal: AbortSignal, body?: unknown): Promise<any> { const response = await fetch(`${session.apiBase}${path}`, { method: body === undefined ? "GET" : "POST", headers: { authorization: `Bearer ${session.token}`, ...(body === undefined ? {} : { "content-type": "application/json" }) }, body: body === undefined ? undefined : JSON.stringify(body), signal }); const value = await response.json(); if (!response.ok) throw new Error(value.error?.code ?? `HTTP_${response.status}`); return value; }
function render(): void { const host = root(); if (!host) return; const selected = deployments.find(d => d.definition.deploymentId === selectedId); const zh = document.documentElement.lang === "zh-CN"; const t = (a: string,b: string) => zh ? a : b;
  host.innerHTML = `<section class="multi-paper-center"><header><div><p class="eyebrow">Paper Only · runtimeApplied=false · exchangeWriteAllowed=false</p><h2>${t("多模拟运行中心", "Simulation runtime center")}</h2><p>${t("切换视图不会启动、停止或改变任何后台实例。", "Changing views never starts, stops, or changes a background instance.")}</p></div><div class="simulation-switch" role="group" aria-label="${t("运行视图", "Runtime view")}"><button data-paper-mode="simulation" aria-pressed="${mode === "simulation"}">${t("模拟", "Simulation")}</button><button data-paper-mode="live" aria-pressed="${mode === "live"}">${t("真实", "Live")}</button></div></header>${mode === "live" ? `<div class="paper-live-unavailable"><strong>Live unavailable</strong><span>Exchange writes OFF</span><p>${t("当前版本只支持独立 Paper 模拟；此视图不产生任何运行时副作用。", "This version supports isolated Paper simulations only; this view has no runtime side effects.")}</p></div>` : simulationMarkup(selected, t)}</section>`;
}
function simulationMarkup(selected: Deployment | undefined, t: (a:string,b:string)=>string): string { const rows = deployments.map(d => `<button class="paper-deployment ${d.definition.deploymentId === selectedId ? "is-selected" : ""}" data-paper-select="${esc(d.definition.deploymentId)}"><strong>${esc(d.definition.name)}</strong><code>${esc(d.state.lifecycle)} · ${esc(d.state.health)}</code><small>${esc(d.definition.strategyVersionId)} · ${d.state.latestCycle} cycles · ${d.state.heartbeatAt ? new Date(d.state.heartbeatAt).toLocaleTimeString() : "—"}</small></button>`).join("") || `<p class="paper-empty">${t("尚无模拟实例。输入服务端已验证的 Strategy Version 创建草案。", "No simulations yet. Enter a server-validated Strategy Version to create a draft.")}</p>`;
  const tabs: Array<[Tab,string,string]> = [["performance","表现","Performance"],["trace","Agent 轨迹","Agent trace"],["trades","交易","Trades"],["configuration","配置与数据","Configuration & data"],["promotion","晋升评估","Promotion assessment"]];
  return `<div class="paper-overview"><div><h3>Simulation Overview</h3><p>${t("曲线和指标仅来自持久化周期/账户投影；没有事实时不会伪造曲线。", "Curves and metrics use only persisted cycle/account projections; no facts means no fabricated curve.")}</p><form data-paper-create><label>${t("名称", "Name")}<input name="name" required maxlength="80"></label><label>Strategy Version<input name="strategyVersionId" required pattern="[a-z0-9._:-]+"></label><label>${t("初始资金", "Initial capital")}<input name="initialCapital" type="number" min="1" value="10000" required></label><label>${t("周期（毫秒）", "Interval (ms)")}<input name="intervalMs" type="number" min="1000" value="60000" required></label><button>${t("创建模拟草案", "Create simulation draft")}</button></form>${error ? `<p class="paper-error">${esc(error)}</p>` : ""}</div><div class="paper-deployment-list">${rows}</div></div>${selected ? `<section class="paper-detail"><header><div><h3>${esc(selected.definition.name)}</h3><code>${esc(selected.definition.deploymentId)}</code></div><div class="paper-actions"><button data-paper-action="preflight">Preflight</button><button data-paper-action="start">Start</button><button data-paper-action="stop">Stop</button><button data-paper-action="archive">Archive</button></div></header><nav>${tabs.map(([id,a,b]) => `<button data-paper-tab="${id}" aria-pressed="${tab===id}">${t(a,b)}</button>`).join("")}</nav><div class="paper-detail-content">${detail(selected,t)}</div></section>` : ""}`; }
function detail(d: Deployment, t:(a:string,b:string)=>string): string { if (tab === "configuration") return `<dl><div><dt>Strategy</dt><dd>${esc(d.definition.strategyVersionId)}</dd></div><div><dt>Source fingerprint</dt><dd>${esc(d.state.sourceFingerprint)}</dd></div><div><dt>Safety</dt><dd>Paper Only · Exchange writes OFF</dd></div></dl>`; if (tab === "promotion") return `<p>${t("只读评估：数据不足；可继续观察。不会自动批准、替换或部署候选。", "Read-only assessment: insufficient data; continue observing. Candidates are never auto-approved, replaced, or deployed.")}</p>`; const kind = tab === "trace" ? "artifacts" : tab === "trades" ? "trades" : "cycles"; const key = `${d.definition.deploymentId}:${kind}`; return `<p>${loaded.has(key) ? t("已按需读取持久投影；当前无可展示事实。", "Persisted projections loaded on demand; no displayable facts yet.") : t("切换到此 Tab 时才读取分页事实。", "Paginated facts are read only when this tab is selected.")}</p>`; }
async function load(): Promise<void> { request?.abort(); const controller = request = new AbortController(), stamp = ++epoch; try { const result = await api("/api/orchestration/paper-deployments?limit=50", controller.signal); if (controller.signal.aborted || stamp !== epoch) return; deployments = result.data; selectedId ??= deployments[0]?.definition.deploymentId; error = ""; } catch (cause) { if (!controller.signal.aborted && stamp === epoch) error = cause instanceof Error ? cause.message : "REQUEST_FAILED"; } render(); }
async function action(name: string): Promise<void> { const selected = deployments.find(d => d.definition.deploymentId === selectedId); if (!selected) return; const controller = request = new AbortController(), stamp = ++epoch; try { await api(`/api/orchestration/paper-deployments/${encodeURIComponent(selected.definition.deploymentId)}/${name}`, controller.signal, { idempotencyKey: idempotency(), sourceFingerprint: selected.state.sourceFingerprint }); if (stamp === epoch) await load(); } catch (cause) { if (!controller.signal.aborted) { error = cause instanceof Error ? cause.message : "ACTION_FAILED"; render(); } } }
document.addEventListener("click", event => { const host = root(), target = (event.target as HTMLElement).closest<HTMLElement>("[data-paper-mode],[data-paper-select],[data-paper-action],[data-paper-tab]"); if (!host || !target || !host.contains(target)) return; if (target.dataset.paperMode) { mode = target.dataset.paperMode as Mode; render(); return; } if (target.dataset.paperSelect) { request?.abort(); epoch++; selectedId = target.dataset.paperSelect; tab = "performance"; render(); return; } if (target.dataset.paperTab) { tab = target.dataset.paperTab as Tab; const d = deployments.find(x=>x.definition.deploymentId===selectedId); const kind = tab === "trace" ? "artifacts" : tab === "trades" ? "trades" : tab === "performance" ? "cycles" : undefined; if (d && kind) { const c = new AbortController(); request?.abort(); request=c; const stamp=++epoch; void api(`/api/orchestration/paper-deployments/${encodeURIComponent(d.definition.deploymentId)}/${kind}?limit=25`,c.signal).then(()=>{ if(stamp===epoch){loaded.add(`${d.definition.deploymentId}:${kind}`);render();} }).catch(()=>{}); } else render(); return; } if (target.dataset.paperAction) void action(target.dataset.paperAction); });
document.addEventListener("submit", event => { const form = event.target as HTMLFormElement; if (!form.matches("[data-paper-create]")) return; event.preventDefault(); const controller = new AbortController(); request?.abort(); request = controller; const values = new FormData(form); void api("/api/orchestration/paper-deployments", controller.signal, { idempotencyKey:idempotency(), name:String(values.get("name")), strategyVersionId:String(values.get("strategyVersionId")), initialCapital:Number(values.get("initialCapital")), intervalMs:Number(values.get("intervalMs")) }).then(load).catch(cause=>{error=cause instanceof Error?cause.message:"CREATE_FAILED";render();}); });
window.addEventListener("tradebot:multi-paper-remount", () => { if (root()) void load(); else { request?.abort(); epoch++; } });
if (root()) void load();
