import { DatabaseSync } from "node:sqlite";
import type { ConnectionDefinition, ConnectionKind, ConnectionVersion } from "../../contracts/src/index.js";
import { ConnectionDefinitionSchema, ConnectionVersionSchema } from "../../contracts/src/index.js";
import type { ConnectionRepository } from "./connection-service.js";
export class SqliteConnectionRepository implements ConnectionRepository {
  constructor(private readonly db: DatabaseSync) { db.exec(`CREATE TABLE IF NOT EXISTS connection_definitions (definition_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, kind TEXT NOT NULL, definition_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS connection_versions (version_id TEXT PRIMARY KEY, definition_id TEXT NOT NULL, version_index INTEGER NOT NULL, version_json TEXT NOT NULL, UNIQUE(definition_id, version_index)); CREATE TRIGGER IF NOT EXISTS connection_versions_update_forbidden BEFORE UPDATE ON connection_versions BEGIN SELECT RAISE(ABORT, 'CONNECTION_VERSION_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS connection_versions_delete_forbidden BEFORE DELETE ON connection_versions BEGIN SELECT RAISE(ABORT, 'CONNECTION_VERSION_IMMUTABLE'); END;`); }
  saveDefinition(value: ConnectionDefinition) { const v = ConnectionDefinitionSchema.parse(value); this.db.prepare("INSERT INTO connection_definitions VALUES (?, ?, ?, ?)").run(v.definitionId, v.createdByActorId, v.kind, JSON.stringify(v)); }
  saveVersion(value: ConnectionVersion) { const v = ConnectionVersionSchema.parse(value); this.db.prepare("INSERT INTO connection_versions VALUES (?, ?, ?, ?)").run(v.versionId, v.definitionId, v.versionIndex, JSON.stringify(v)); }
  list(actorId: string, kind?: ConnectionKind) { const rows = (kind ? this.db.prepare("SELECT d.definition_json, v.version_json FROM connection_definitions d JOIN connection_versions v ON v.definition_id=d.definition_id WHERE d.actor_id=? AND d.kind=? ORDER BY d.definition_id, v.version_index DESC").all(actorId, kind) : this.db.prepare("SELECT d.definition_json, v.version_json FROM connection_definitions d JOIN connection_versions v ON v.definition_id=d.definition_id WHERE d.actor_id=? ORDER BY d.definition_id, v.version_index DESC").all(actorId)) as Array<{ definition_json: string; version_json: string }>; const seen = new Set<string>(); return rows.flatMap((row) => { const definition = ConnectionDefinitionSchema.parse(JSON.parse(row.definition_json)); if (seen.has(definition.definitionId)) return []; seen.add(definition.definitionId); return [{ definition, version: ConnectionVersionSchema.parse(JSON.parse(row.version_json)) }]; }); }
}
