import { DatabaseSync } from "node:sqlite";
import type { AgentDefinition, AgentVersion, AgentCategory } from "../../contracts/src/index.js";
import { AgentDefinitionSchema, AgentVersionSchema } from "../../contracts/src/index.js";
import type { AgentDefinitionRepository } from "./agent-definition-service.js";
export class SqliteAgentDefinitionRepository implements AgentDefinitionRepository {
  constructor(private readonly db: DatabaseSync) { db.exec(`CREATE TABLE IF NOT EXISTS agent_definitions (definition_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, category TEXT NOT NULL, definition_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS agent_versions (version_id TEXT PRIMARY KEY, definition_id TEXT NOT NULL, version_index INTEGER NOT NULL, fingerprint TEXT NOT NULL UNIQUE, version_json TEXT NOT NULL, UNIQUE(definition_id, version_index)); CREATE INDEX IF NOT EXISTS agent_definitions_actor ON agent_definitions(actor_id, category); CREATE INDEX IF NOT EXISTS agent_versions_definition ON agent_versions(definition_id, version_index); CREATE TRIGGER IF NOT EXISTS agent_versions_update_forbidden BEFORE UPDATE ON agent_versions BEGIN SELECT RAISE(ABORT, 'AGENT_VERSION_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_versions_delete_forbidden BEFORE DELETE ON agent_versions BEGIN SELECT RAISE(ABORT, 'AGENT_VERSION_IMMUTABLE'); END;`); }
  saveDefinition(value: AgentDefinition) { const v = AgentDefinitionSchema.parse(value); this.db.prepare("INSERT INTO agent_definitions VALUES (?, ?, ?, ?)").run(v.definitionId, v.createdByActorId, v.category, JSON.stringify(v)); }
  saveVersion(value: AgentVersion) { const v = AgentVersionSchema.parse(value); this.db.prepare("INSERT INTO agent_versions VALUES (?, ?, ?, ?, ?)").run(v.versionId, v.definitionId, v.versionIndex, v.fingerprint, JSON.stringify(v)); }
  getDefinition(id: string) { const row = this.db.prepare("SELECT definition_json FROM agent_definitions WHERE definition_id = ?").get(id) as { definition_json: string } | undefined; return row ? AgentDefinitionSchema.parse(JSON.parse(row.definition_json)) : undefined; }
  getVersion(id: string) { const row = this.db.prepare("SELECT version_json FROM agent_versions WHERE version_id = ?").get(id) as { version_json: string } | undefined; return row ? AgentVersionSchema.parse(JSON.parse(row.version_json)) : undefined; }
  latest(id: string) { const row = this.db.prepare("SELECT version_json FROM agent_versions WHERE definition_id = ? ORDER BY version_index DESC LIMIT 1").get(id) as { version_json: string } | undefined; return row ? AgentVersionSchema.parse(JSON.parse(row.version_json)) : undefined; }
  listDefinitions(actorId: string, category?: AgentCategory) { const rows = (category ? this.db.prepare("SELECT definition_json FROM agent_definitions WHERE actor_id = ? AND category = ? ORDER BY definition_id").all(actorId, category) : this.db.prepare("SELECT definition_json FROM agent_definitions WHERE actor_id = ? ORDER BY definition_id").all(actorId)) as { definition_json: string }[]; return rows.map((row) => AgentDefinitionSchema.parse(JSON.parse(row.definition_json))); }
  listVersions(id: string) { return (this.db.prepare("SELECT version_json FROM agent_versions WHERE definition_id = ? ORDER BY version_index").all(id) as { version_json: string }[]).map((row) => AgentVersionSchema.parse(JSON.parse(row.version_json))); }
}
