import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
import type { AgentDefinition, AgentVersion, AgentCategory, AgentLifecycleStatus, AgentTestEvidence } from "../../contracts/src/index.js";
import { AgentDefinitionSchema, AgentVersionSchema, AgentTestEvidenceSchema } from "../../contracts/src/index.js";
import type { AgentDefinitionRepository } from "./agent-definition-service.js";
export class SqliteAgentDefinitionRepository implements AgentDefinitionRepository {
  constructor(private readonly db: DatabaseSync) { db.exec(`CREATE TABLE IF NOT EXISTS agent_definitions (definition_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, category TEXT NOT NULL, definition_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS agent_versions (version_id TEXT PRIMARY KEY, definition_id TEXT NOT NULL, version_index INTEGER NOT NULL, fingerprint TEXT NOT NULL UNIQUE, version_json TEXT NOT NULL, UNIQUE(definition_id, version_index)); CREATE TABLE IF NOT EXISTS agent_idempotency (actor_id TEXT NOT NULL, scope TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_fingerprint TEXT NOT NULL, response_json TEXT NOT NULL, PRIMARY KEY(actor_id, scope, idempotency_key)); CREATE TABLE IF NOT EXISTS agent_governance_facts (fact_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, version_id TEXT NOT NULL, fingerprint TEXT NOT NULL, status TEXT NOT NULL, occurred_at TEXT NOT NULL, fact_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS agent_test_evidence (test_run_id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, version_id TEXT NOT NULL, evidence_json TEXT NOT NULL); CREATE INDEX IF NOT EXISTS agent_definitions_actor ON agent_definitions(actor_id, category); CREATE INDEX IF NOT EXISTS agent_versions_definition ON agent_versions(definition_id, version_index); CREATE INDEX IF NOT EXISTS agent_governance_version ON agent_governance_facts(version_id, occurred_at); CREATE INDEX IF NOT EXISTS agent_test_evidence_version ON agent_test_evidence(version_id); CREATE TRIGGER IF NOT EXISTS agent_versions_update_forbidden BEFORE UPDATE ON agent_versions BEGIN SELECT RAISE(ABORT, 'AGENT_VERSION_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_versions_delete_forbidden BEFORE DELETE ON agent_versions BEGIN SELECT RAISE(ABORT, 'AGENT_VERSION_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_governance_update_forbidden BEFORE UPDATE ON agent_governance_facts BEGIN SELECT RAISE(ABORT, 'AGENT_GOVERNANCE_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_governance_delete_forbidden BEFORE DELETE ON agent_governance_facts BEGIN SELECT RAISE(ABORT, 'AGENT_GOVERNANCE_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_test_evidence_update_forbidden BEFORE UPDATE ON agent_test_evidence BEGIN SELECT RAISE(ABORT, 'AGENT_TEST_EVIDENCE_IMMUTABLE'); END; CREATE TRIGGER IF NOT EXISTS agent_test_evidence_delete_forbidden BEFORE DELETE ON agent_test_evidence BEGIN SELECT RAISE(ABORT, 'AGENT_TEST_EVIDENCE_IMMUTABLE'); END;`); }
  saveDefinition(value: AgentDefinition) { const v = AgentDefinitionSchema.parse(value); this.db.prepare("INSERT INTO agent_definitions VALUES (?, ?, ?, ?)").run(v.definitionId, v.createdByActorId, v.category, JSON.stringify(v)); }
  saveVersion(value: AgentVersion) { const v = AgentVersionSchema.parse(value); this.db.prepare("INSERT INTO agent_versions VALUES (?, ?, ?, ?, ?)").run(v.versionId, v.definitionId, v.versionIndex, v.fingerprint, JSON.stringify(v)); }
  getDefinition(id: string) { const row = this.db.prepare("SELECT definition_json FROM agent_definitions WHERE definition_id = ?").get(id) as { definition_json: string } | undefined; return row ? AgentDefinitionSchema.parse(JSON.parse(row.definition_json)) : undefined; }
  getVersion(id: string) { const row = this.db.prepare("SELECT version_json FROM agent_versions WHERE version_id = ?").get(id) as { version_json: string } | undefined; return row ? AgentVersionSchema.parse(JSON.parse(row.version_json)) : undefined; }
  latest(id: string) { const row = this.db.prepare("SELECT version_json FROM agent_versions WHERE definition_id = ? ORDER BY version_index DESC LIMIT 1").get(id) as { version_json: string } | undefined; return row ? AgentVersionSchema.parse(JSON.parse(row.version_json)) : undefined; }
  listDefinitions(actorId: string, category?: AgentCategory) { const rows = (category ? this.db.prepare("SELECT definition_json FROM agent_definitions WHERE actor_id = ? AND category = ? ORDER BY definition_id").all(actorId, category) : this.db.prepare("SELECT definition_json FROM agent_definitions WHERE actor_id = ? ORDER BY definition_id").all(actorId)) as { definition_json: string }[]; return rows.map((row) => AgentDefinitionSchema.parse(JSON.parse(row.definition_json))); }
  listVersions(id: string) { return (this.db.prepare("SELECT version_json FROM agent_versions WHERE definition_id = ? ORDER BY version_index").all(id) as { version_json: string }[]).map((row) => AgentVersionSchema.parse(JSON.parse(row.version_json))); }
  getReplay(actorId: string, scope: string, idempotencyKey: string) { const row = this.db.prepare("SELECT request_fingerprint, response_json FROM agent_idempotency WHERE actor_id = ? AND scope = ? AND idempotency_key = ?").get(actorId, scope, idempotencyKey) as { request_fingerprint: string; response_json: string } | undefined; if (!row) return undefined; const value = JSON.parse(row.response_json) as { definition?: AgentDefinition; version: AgentVersion }; return { requestFingerprint: row.request_fingerprint, response: { ...(value.definition ? { definition: AgentDefinitionSchema.parse(value.definition) } : {}), version: AgentVersionSchema.parse(value.version) } }; }
  saveReplay(actorId: string, scope: string, idempotencyKey: string, requestFingerprint: string, response: { definition?: AgentDefinition; version: AgentVersion }) { this.db.prepare("INSERT INTO agent_idempotency VALUES (?, ?, ?, ?, ?)").run(actorId, scope, idempotencyKey, requestFingerprint, JSON.stringify(response)); }
  saveGovernance(actorId: string, versionId: string, fingerprint: string, status: AgentLifecycleStatus, occurredAt: string) { this.db.prepare("INSERT INTO agent_governance_facts VALUES (?, ?, ?, ?, ?, ?, ?)").run(`agent-governance:${randomUUID()}`, actorId, versionId, fingerprint, status, occurredAt, JSON.stringify({ status, actorId, occurredAt })); }
  governance(versionId: string): { status: AgentLifecycleStatus; actorId: string; occurredAt: string }[] { return (this.db.prepare("SELECT status, actor_id, occurred_at FROM agent_governance_facts WHERE version_id = ? ORDER BY occurred_at").all(versionId) as { status: AgentLifecycleStatus; actor_id: string; occurred_at: string }[]).map((row) => ({ status: row.status, actorId: row.actor_id, occurredAt: row.occurred_at })); }
  saveEvidence(value: AgentTestEvidence) { const v = AgentTestEvidenceSchema.parse(value); this.db.prepare("INSERT INTO agent_test_evidence VALUES (?, ?, ?, ?)").run(v.testRunId, v.createdByActorId, v.agentVersionId, JSON.stringify(v)); }
  evidence(actorId: string, versionId: string) { return (this.db.prepare("SELECT evidence_json FROM agent_test_evidence WHERE actor_id = ? AND version_id = ? ORDER BY test_run_id DESC").all(actorId, versionId) as { evidence_json: string }[]).map((row) => AgentTestEvidenceSchema.parse(JSON.parse(row.evidence_json))); }
}
