import apiClient from './index';

export type StrategyDataRequirement = { id:string; type:string; kind:'kline'|'news'|'fundamentals'|'other'; sourceIds:string[]; markets:string[]; frequency:string; lookback:string|number; required:boolean; usage:string; onMissing:'fail'|'degrade' };
export type StrategyBacktestReadiness = { ready:boolean; code:string; message:string; symbolCount?:number };
export type StrategySummary = { id:number; name:string; description?:string; lifecycleStatus:string; revision:number; activeDraftVersionId?:number|null; currentPublishedVersionId?:number|null; currentPublishedVersionNumber?:number|null; currentStrategyPurpose?:StrategyPurpose|null; currentOutputContract?:StrategyOutputContract|null; currentObjective?:string|null; productRole?:'kernel'|'configured'; kernelVersionId?:number|null; kernelRuntime?:string|null; kernelEntrypoint?:string|null; kernelExecutionStatus?:'ready'|'awaiting_isolated_executor'|null; kernelDataRequirements?:StrategyDataRequirement[]; backtestReadiness?:StrategyBacktestReadiness; isBuiltIn?:boolean; sourceSystem?:'daily_stock_analysis'|'user'|string; createdAt?:string; updatedAt:string; archivedAt?:string|null };
export type Agent = { id:string; lineageId:string; agentTemplateId?:number|null; agentTemplateVersion?:number|null; agentType:'INPUT'|'SCREENING'|'ANALYSIS'|'DECISION'|'REFLECTION'; name:string; role:string; systemPrompt:string; promptTemplate:string; modelProfileId?:string|null; fallbackModelProfileId?:string|null; executionMode:string; toolPermissions:string[]; dataPermissions:string[]; inputSchema:Record<string, unknown>; outputSchema:Record<string, unknown>; timeoutSeconds:number; maxRetries:number; required:boolean; failurePolicy:string; costLimit:string; positionX:number; positionY:number };
export type Connection = { id:string; sourceAgentId:string; targetAgentId:string; connectionType:'DATA_FLOW'|'POST_RUN_CONTEXT'; condition?:string|null; fieldMapping:Record<string, unknown> };
export type ScreeningPolicy = { strategy:string; market:string; maxCandidates:number };
export type StrategyPurpose = 'research_report'|'candidate_screening'|'trading_decision';
export type StrategyOutputContract = 'ResearchReport'|'CandidateList'|'DecisionProposal'|'UnknownOutput';
export type StrategyPackageParameter = { name:string; type:'string'|'integer'|'number'|'boolean'; default?:unknown; minimum?:number; maximum?:number; enum?:unknown[]; description?:string; required?:boolean };
export type StrategyPackageMetadata = { kind:'uploaded_package'|'builtin_python'; fileName:string; sha256:string; declaredVersion:string; runtime:string; entrypoint:string; executionStatus:'awaiting_isolated_executor'|'ready'; outputContract:StrategyOutputContract; configurable:{markets:string[];timeframes:string[];runIntervals:string[]}; parameters:StrategyPackageParameter[]; dataRequirements:StrategyDataRequirement[]; inputSchema?:Record<string,unknown>; outputSchema?:Record<string,unknown>; documentation:string; dependencyWarnings:string[] };
export type StrategyVersion = { id:number; strategyId:number; status:string; versionNumber?:number|null; basedOnVersionId?:number|null; changeLog?:string|null; agentWorkflowVersionId?:number|null; strategyPurpose?:StrategyPurpose; outputContract?:StrategyOutputContract; productRole?:'kernel'|'configured'; kernelVersionId?:number|null; agentCount?:number; connectionCount?:number; immutable:boolean; revision:number; objective?:string|null; marketScope:Record<string, unknown>; timeHorizon?:string|null; decisionPolicy:Record<string, unknown>; riskPolicy:Record<string, unknown>; memoryPolicy:Record<string, unknown>; dataPermissionSnapshot:Record<string, unknown>; screeningPolicy?:ScreeningPolicy; strategyPackage?:StrategyPackageMetadata|null; agents:Agent[]; connections:Connection[]; createdAt:string; publishedAt?:string|null };
export type ValidationIssue = { code:string; message:string; agent_ids?:string[]; connection_ids?:string[]; field_path?:string|null; suggestion?:string|null };
export type ValidationResult = { valid:boolean; versionId:number; revision:number; validatedAt:string; errors:ValidationIssue[]; warnings:ValidationIssue[] };
export type AgentTemplate = { templateId:number; name:string; description?:string; agentType:Agent['agentType']; currentVersion:number; supportedTools:string[]; supportedDataTypes:string[]; archived:boolean; updatedAt:string };
export type AgentTemplateDetail = AgentTemplate & { templateVersion:number; defaultRole:string; defaultSystemPrompt:string; defaultPromptTemplate:string; inputSchema:Record<string,unknown>; outputSchema:Record<string,unknown> };
export type AgentWorkflowSummary = { id:number; name:string; description?:string|null; lifecycleStatus:'draft'|'published'|'archived'; revision:number; activeDraftVersionId?:number|null; currentPublishedVersionId?:number|null; currentPublishedVersionNumber?:number|null; agentCount:number; connectionCount:number; archivedAt?:string|null; createdAt:string; updatedAt:string };
export type AgentWorkflowVersion = { id:number; workflowId:number; workflowName?:string; workflowDescription?:string|null; status:'DRAFT'|'PUBLISHED'; versionNumber?:number|null; basedOnVersionId?:number|null; changeLog?:string|null; revision:number; immutable:boolean; agentCount:number; connectionCount:number; outputContract?:StrategyOutputContract; agents:Agent[]; connections:Connection[]; createdAt:string; updatedAt:string; publishedAt?:string|null };
export type AgentWorkflowValidation = { valid:boolean; workflowVersionId:number; revision:number; validatedAt:string; errors:ValidationIssue[]; warnings:ValidationIssue[] };
export type VersionDiff = { summary:Record<string,number|boolean>; changes:Array<{category:string;agentName?:string;agentLineageId?:string;field?:string;before?:unknown;after?:unknown;sensitive?:boolean}> };
export type StrategyTemplate = { id:string; name:string; description:string; recommended_sources?:string[]; risk_rules?:Record<string,unknown>; position_rules?:Record<string,unknown> };
export type RunnableStrategyVersion = { strategyId:number; strategyName:string; strategyDescription?:string|null; versionId:number; versionNumber?:number|null; publishedAt?:string|null; agentCount:number; connectionCount:number; validationStatus?:StrategyValidationVersionStatus['status']; latestValidationExperimentId?:number|null; validatedAt?:string|null; strategyPurpose?:StrategyPurpose; outputContract?:StrategyOutputContract; kernelRuntime?:string|null; kernelEntrypoint?:string|null; kernelExecutionStatus?:string|null; market?:string|null; timeHorizon?:string|null };
export type PublishedStrategyRun = { id:number; strategyId:number; strategyName:string; strategyVersionId:number; versionNumber?:number|null; status:'queued'|'running'|'completed'|'failed'|'cancelled'; executionMode:'preview'|'paper'; inputSnapshot:Record<string,unknown>; resultSnapshot?:Record<string,unknown>|null; errorMessage?:string|null; startedAt?:string|null; completedAt?:string|null; createdAt:string; updatedAt:string; outputContract?:StrategyOutputContract; kernelRuntime?:string|null };
export type AgentRunProgress = { agentId?:string; agentName?:string; agentType?:string; status:'queued'|'running'|'completed'|'failed'|'cancelled'|string; durationMs?:number|null };
export type AutomaticStrategyRunBatch = { id:number; strategyId:number; strategyName:string; strategyVersionId:number; versionNumber?:number|null; status:'queued'|'running'|'completed'|'completed_with_failures'|'failed'|'cancelled'; screeningPolicy:ScreeningPolicy; screeningRunId?:string|null; candidateCount:number; candidates:Array<{runId:number;code:string;name?:string|null;screenScore?:number|null;status:PublishedStrategyRun['status']}>; screening:Record<string,unknown>;errorMessage?:string|null;startedAt?:string|null;completedAt?:string|null;createdAt:string;updatedAt:string;outputContract?:StrategyOutputContract;kernelRuntime?:string|null };
export type ContinuousStrategyRunControl = { id:number; strategyVersionId:number; status:'running'|'paused'|'terminated'; intervalSeconds:number; lastBatchId?:number|null; nextRunAt?:string|null; lastStartedAt?:string|null; lastCompletedAt?:string|null; errorMessage?:string|null; createdAt:string; updatedAt:string };
export type StrategyValidationConfig = { startDate:string; endDate:string; initialCapital:number; commissionRate:number; minimumCommission:number; slippageRate:number; executionRule:'next_open'; rebalanceFrequency:'daily'|'weekly'|'monthly'; market:'cn'|'hk'|'us'; universeMode:'strategy'|'override'; experimentPurpose:'validation'|'diagnostic'; maxPositions:number; maxUniverseSize:number; symbols:string[]; resolvedUniverseMode?:string };
export type StrategyValidationMetrics = { initialCapital:number; finalEquity:number; cumulativeReturn:number; annualizedReturn?:number|null; maxDrawdown:number; annualizedVolatility:number; sharpeRatio?:number|null; tradeCount:number; closedTradeCount:number; winRate?:number|null; turnover?:number|null };
export type StrategyValidationResult = { engineVersion:string; methodology:string; conclusion:'observational'|'passed'; metrics:StrategyValidationMetrics; equityCurve:Array<{date:string;equity:number;cash:number;positionCount:number}>; trades:Array<{code:string;side:'buy'|'sell';quantity:number;signalDate:string;executionDate:string;rawPrice:number;fillPrice:number;grossAmount:number;commission:number;stampDuty?:number;transferFee?:number;totalFees?:number;slippageCost:number;realizedPnl?:number|null}>; finalPositions:Array<{code:string;quantity:number;averagePrice:number;entryFee:number}>; marketSnapshot:{sha256:string;hashAlgorithm?:string;barCount:number;symbolCount:number;sources:string[];adjustmentModes?:string[];sourceRecordedFrom?:string|null;sourceRecordedTo?:string|null;firstDate:string;lastDate:string}; dataQuality?:{complete:boolean;requestedStartDate:string;requestedEndDate:string;actualReplayStartDate?:string|null;actualReplayEndDate?:string|null;symbols:Array<{requestedSymbol:string;resolvedSymbol?:string|null;lookbackBars:number;replayBars:number;minimumReplayBars:number;complete:boolean}>}; strategyReplay:{screeningPolicy:string;rebalanceFrequency:string;executionRule:string;maxPositions:number;maxPositionPercent?:number;universeMode?:string;experimentPurpose?:'validation'|'diagnostic';skippedExecutions?:Array<Record<string,unknown>>}; strategyCoverage?:{level:'partial'|'full';executedComponents:string[];omittedComponents:string[]}; costModel?:Record<string,unknown>; limitations:string[] };
export type StrategyValidationExperiment = { id:number; strategyId?:number|null; strategyName?:string|null; strategyVersionId:number; versionNumber?:number|null; versionStatus?:string|null; versionRevision:number; status:'queued'|'running'|'completed'|'failed'; engineVersion:string; config:StrategyValidationConfig; result?:StrategyValidationResult|null; barCount:number; inputSnapshotHash?:string|null; integrityStatus?:'verified'|'legacy_unverified'|'failed'; errorMessage?:string|null; startedAt?:string|null; completedAt?:string|null; createdAt?:string|null; updatedAt?:string|null };
export type StrategyValidationComparisonSide = { experimentId:number; strategyVersionId:number; versionNumber?:number|null; versionStatus?:string|null; completedAt?:string|null; inputSnapshotHash:string; symbolCount:number; metrics:StrategyValidationMetrics };
export type StrategyValidationComparisonMetric = { key:string; label:string; format:'percent'|'number'|'integer'|'currency'; preference:'higher'|'lower'|'neutral'; baselineValue?:number|null; targetValue?:number|null; delta?:number|null };
export type StrategyValidationComparison = { strategyId:number; strategyName:string; baseline:StrategyValidationComparisonSide; target:StrategyValidationComparisonSide; metrics:StrategyValidationComparisonMetric[]; comparisonBasis:{ startDate:string; endDate:string; actualReplayStartDate?:string|null; actualReplayEndDate?:string|null; market:string; engineVersion:string; methodology:string; snapshotMode:'exact_snapshot'|'aligned_independent_snapshots'; sameUniverse:boolean; baselineSources:string[]; targetSources:string[]; costAssumptions:Record<string,number>; executionAssumptions:Record<string,string|number> } };
export type StrategyValidationVersionStatus = { strategyVersionId:number; versionRevision:number; status:'not_started'|'queued'|'running'|'completed'|'validated'|'failed'; latestExperimentId?:number|null; latestCompletedExperimentId?:number|null; completedAt?:string|null; validatedAt?:string|null };
export type StrategyDeletionImpact = { strategyId:number; strategyName:string; hasPublishedVersion:boolean; publishedVersionCount:number; isRunning:boolean; activeContinuousRunCount:number; activeResearchRunCount:number; requiresConfirmation:boolean };
export type StrategyDeletionResult = { strategyId:number; deleted:boolean; deletedAt:string; wasPublished:boolean; terminatedContinuousRuns:number; cancelledResearchRuns:number; historyRetained:boolean };
export type StrategyDataSource = { id?:number; sourceId:string; name:string; kind:'kline'|'news'|'fundamentals'|'other'; description?:string|null; connectionKey:string; required:boolean; builtIn:boolean; selectable:boolean; availability:'system_managed'|'configured'|'unconfigured'|'registered'; selectionMode?:'automatic'|'provider'|'local'; providerName?:string; markets?:string[]; createdAt?:string; updatedAt?:string };

const root='/api/v1/simulation/definition';
export const strategyWorkspaceApi={
  async listStrategies(includeArchived=false){const {data}=await apiClient.get<StrategySummary[]>(`${root}/strategies`,{params:{include_archived:includeArchived}});return data;},
  async createStrategy(name:string,description='',templateId?:string,basedOnVersionId?:number){const {data}=await apiClient.post<{strategy:StrategySummary;draft:StrategyVersion}>(`${root}/strategies`,{name,description,templateId,basedOnVersionId});return data;},
  async createConfiguredStrategy(kernelVersionId:number,name:string,description=''){const {data}=await apiClient.post<{strategy:StrategySummary;draft:StrategyVersion}>(`${root}/strategies`,{name,description,kernelVersionId});return data;},
  async intakeStrategyPackage(file:File){const payload=new FormData();payload.append('file',file);const {data}=await apiClient.post<{strategy:StrategySummary;draft:StrategyVersion;package:StrategyPackageMetadata;warnings:string[]}>(`${root}/strategy-packages/intake`,payload);return data;},
  async getStrategy(id:number){const {data}=await apiClient.get<StrategySummary & {versions:StrategyVersion[]}>(`${root}/strategies/${id}`);return data;},
  async getVersion(id:number){const {data}=await apiClient.get<StrategyVersion>(`${root}/strategy-versions/${id}`);return data;},
  async executeKernel(id:number,payload:{inputs?:Record<string,unknown>;data?:Record<string,unknown>;mode?:'preview'|'research'|'backtest';asOf?:string}){const {data}=await apiClient.post<Record<string,unknown>>(`${root}/strategy-versions/${id}/execute-kernel`,payload);return data;},
  async saveDraft(version:StrategyVersion, strategy:{name:string;description?:string}){const {data}=await apiClient.put(`${root}/strategy-versions/${version.id}/draft`,{revision:version.revision,strategy,version:{objective:version.objective,strategyPurpose:version.strategyPurpose||'trading_decision',marketScope:version.marketScope,timeHorizon:version.timeHorizon,decisionPolicy:version.decisionPolicy,riskPolicy:version.riskPolicy,memoryPolicy:version.memoryPolicy,dataPermissionSnapshot:version.dataPermissionSnapshot,screeningPolicy:version.screeningPolicy||{strategy:'dual_low',market:'cn',maxCandidates:3},agentWorkflowVersionId:version.agentWorkflowVersionId},agents:version.agents,connections:version.connections});return data as {draft:StrategyVersion;revision:number};},
  async validate(id:number){const {data}=await apiClient.post<ValidationResult>(`${root}/strategy-versions/${id}/validate`);return data;},
  async publish(id:number,revision:number,changeLog:string,warnings:string[],validationExperimentId?:number){const {data}=await apiClient.post(`${root}/strategy-versions/${id}/publish`,{revision,changeLog,acknowledgedWarningCodes:warnings,idempotencyKey:crypto.randomUUID(),validationExperimentId});return data;},
  async createDraft(strategyId:number,basedOnVersionId:number){const {data}=await apiClient.post<StrategyVersion>(`${root}/strategies/${strategyId}/drafts`,{basedOnVersionId});return data;},
  async diff(id:number,against:number){const {data}=await apiClient.get<VersionDiff>(`${root}/strategy-versions/${id}/diff`,{params:{against}});return data;},
  async archive(id:number){const {data}=await apiClient.post<StrategySummary>(`${root}/strategies/${id}/archive`);return data;},
  async getDeletionImpact(id:number){const {data}=await apiClient.get<StrategyDeletionImpact>(`${root}/strategies/${id}/deletion-impact`);return data;},
  async deleteStrategy(id:number,confirmed=false){const {data}=await apiClient.delete<StrategyDeletionResult>(`${root}/strategies/${id}`,{params:{confirmed}});return data;},
  async listAgentTemplates(agentType?:Agent['agentType'], q?:string){const {data}=await apiClient.get<AgentTemplate[]>(`${root}/agent-templates`,{params:{agent_type:agentType,q}});return data;},
  async createAgentTemplate(payload:{name:string;description?:string;agentType:Exclude<Agent['agentType'],'INPUT'>;defaultRole:string;defaultSystemPrompt:string;defaultPromptTemplate?:string;inputSchema?:Record<string,unknown>;outputSchema?:Record<string,unknown>;supportedTools?:string[];supportedDataTypes?:string[]}){const {data}=await apiClient.post<AgentTemplateDetail>(`${root}/agent-templates`,payload);return data;},
  async updateAgentTemplate(id:number,payload:Partial<Omit<AgentTemplateDetail,'templateId'|'templateVersion'|'archived'|'updatedAt'>> & {currentVersion:number}){const {data}=await apiClient.put<AgentTemplateDetail>(`${root}/agent-templates/${id}`,payload);return data;},
  async archiveAgentTemplate(id:number){const {data}=await apiClient.delete<AgentTemplate & {archived:true}>(`${root}/agent-templates/${id}`);return data;},
  async listAgentWorkflows(includeArchived=false){const {data}=await apiClient.get<AgentWorkflowSummary[]>(`${root}/agent-workflows`,{params:{include_archived:includeArchived}});return data;},
  async createAgentWorkflow(payload:{name:string;description?:string;basedOnStrategyVersionId?:number;agents?:Agent[];connections?:Connection[]}){const {data}=await apiClient.post<{workflow:AgentWorkflowSummary;draft:AgentWorkflowVersion}>(`${root}/agent-workflows`,payload);return data;},
  async getAgentWorkflow(id:number){const {data}=await apiClient.get<AgentWorkflowSummary & {versions:AgentWorkflowVersion[]}>(`${root}/agent-workflows/${id}`);return data;},
  async listPublishedAgentWorkflowVersions(currentOnly=true){const {data}=await apiClient.get<AgentWorkflowVersion[]>(`${root}/agent-workflows/published-versions`,{params:{current_only:currentOnly}});return data;},
  async getAgentWorkflowVersion(id:number){const {data}=await apiClient.get<AgentWorkflowVersion>(`${root}/agent-workflow-versions/${id}`);return data;},
  async saveAgentWorkflowDraft(version:AgentWorkflowVersion,workflow:{name:string;description?:string}){const {data}=await apiClient.put<{draft:AgentWorkflowVersion;revision:number}>(`${root}/agent-workflow-versions/${version.id}/draft`,{revision:version.revision,workflow,agents:version.agents,connections:version.connections});return data;},
  async validateAgentWorkflow(id:number){const {data}=await apiClient.post<AgentWorkflowValidation>(`${root}/agent-workflow-versions/${id}/validate`);return data;},
  async publishAgentWorkflow(id:number,revision:number,changeLog:string){const {data}=await apiClient.post<AgentWorkflowVersion>(`${root}/agent-workflow-versions/${id}/publish`,{revision,changeLog,idempotencyKey:crypto.randomUUID()});return data;},
  async createAgentWorkflowDraft(workflowId:number,basedOnVersionId:number){const {data}=await apiClient.post<AgentWorkflowVersion>(`${root}/agent-workflows/${workflowId}/drafts`,{basedOnVersionId});return data;},
  async archiveAgentWorkflow(workflowId:number){const {data}=await apiClient.delete<{workflowId:number;archived:true;strategyVersionReferenceCount:number;historyRetained:true}>(`${root}/agent-workflows/${workflowId}`);return data;},
  async listDataSources(){const {data}=await apiClient.get<StrategyDataSource[]>(`${root}/data-sources`);return data;},
  async createDataSource(payload:{name:string;description?:string;connectionKey:string;kind:StrategyDataSource['kind'];markets:string[]}){const {data}=await apiClient.post<StrategyDataSource>(`${root}/data-sources`,payload);return data;},
  async archiveDataSource(id:number){const {data}=await apiClient.delete<StrategyDataSource & {archived:boolean}>(`${root}/data-sources/${id}`);return data;},
  async getAgentTemplate(id:number){const {data}=await apiClient.get<AgentTemplateDetail>(`${root}/agent-templates/${id}`);return data;},
  async diffPreview(id:number, localDraft:StrategyVersion){const {data}=await apiClient.post<VersionDiff>(`${root}/strategy-versions/${id}/diff-preview`,{localDraft});return data;},
  async forkLocal(id:number,payload:{baseRevision:number;newStrategyName:string;newStrategyDescription?:string;localDraft:StrategyVersion;idempotencyKey:string}){const {data}=await apiClient.post<{newStrategyId:number;newDraftVersionId:number;initialRevision:number;idempotent:boolean}>(`${root}/strategy-versions/${id}/fork-local`,payload);return data;},
  async listStrategyTemplates(){const {data}=await apiClient.get<{items:StrategyTemplate[]}>('/api/v1/simulation/templates');return data.items;},
  async listRunnableVersions(){const {data}=await apiClient.get<RunnableStrategyVersion[]>(`${root}/runnable-versions`);return data;},
  async createPublishedRun(strategyVersionId:number, stockCode:string){const {data}=await apiClient.post<PublishedStrategyRun>(`${root}/runs`,{strategyVersionId,inputSnapshot:{stockCode}});return data;},
  async executePublishedRun(runId:number){const {data}=await apiClient.post<PublishedStrategyRun>(`${root}/runs/${runId}/execute`);return data;},
  async listPublishedRuns(){const {data}=await apiClient.get<{items:PublishedStrategyRun[]}>(`${root}/runs`);return data.items;},
  async getPublishedRun(runId:number){const {data}=await apiClient.get<PublishedStrategyRun>(`${root}/runs/${runId}`);return data;},
  async createAutomaticRun(strategyVersionId:number){const {data}=await apiClient.post<AutomaticStrategyRunBatch>(`${root}/automatic-runs`,{strategyVersionId});return data;},
  async listAutomaticRuns(){const {data}=await apiClient.get<{items:AutomaticStrategyRunBatch[]}>(`${root}/automatic-runs`);return data.items;},
  async getAutomaticRun(batchId:number){const {data}=await apiClient.get<AutomaticStrategyRunBatch>(`${root}/automatic-runs/${batchId}`);return data;},
  async startContinuousRun(strategyVersionId:number, intervalSeconds:number){const {data}=await apiClient.post<ContinuousStrategyRunControl>(`${root}/continuous-runs`,{strategyVersionId,intervalSeconds});return data;},
  async listContinuousRuns(){const {data}=await apiClient.get<{items:ContinuousStrategyRunControl[]}>(`${root}/continuous-runs`);return data.items;},
  async pauseContinuousRun(controlId:number){const {data}=await apiClient.post<ContinuousStrategyRunControl>(`${root}/continuous-runs/${controlId}/pause`);return data;},
  async terminateContinuousRun(controlId:number){const {data}=await apiClient.post<ContinuousStrategyRunControl>(`${root}/continuous-runs/${controlId}/terminate`);return data;},
  async createValidationExperiment(strategyVersionId:number,config:StrategyValidationConfig){const {data}=await apiClient.post<StrategyValidationExperiment>(`${root}/validation-experiments`,{strategyVersionId,config,idempotencyKey:crypto.randomUUID()});return data;},
  async executeValidationExperiment(experimentId:number){const {data}=await apiClient.post<StrategyValidationExperiment>(`${root}/validation-experiments/${experimentId}/execute`);return data;},
  async listValidationExperiments(strategyVersionId:number){const {data}=await apiClient.get<{items:StrategyValidationExperiment[]}>(`${root}/validation-experiments`,{params:{strategyVersionId}});return data.items;},
  async listValidationComparisonCandidates(strategyId:number){const {data}=await apiClient.get<{items:StrategyValidationExperiment[]}>(`${root}/validation-comparison-candidates`,{params:{strategyId}});return data.items;},
  async compareValidationExperiments(baselineExperimentId:number,targetExperimentId:number){const {data}=await apiClient.post<StrategyValidationComparison>(`${root}/validation-comparisons`,{baselineExperimentId,targetExperimentId});return data;},
  async getValidationExperiment(experimentId:number){const {data}=await apiClient.get<StrategyValidationExperiment>(`${root}/validation-experiments/${experimentId}`);return data;},
  async getValidationStatus(strategyVersionId:number){const {data}=await apiClient.get<StrategyValidationVersionStatus>(`${root}/strategy-versions/${strategyVersionId}/validation-status`);return data;},
};

export const blankAgent=(type:Agent['agentType']):Agent=>({id:crypto.randomUUID(),lineageId:crypto.randomUUID(),agentType:type,name:`新的 ${type} Agent`,role:'请描述该 Agent 的职责。',systemPrompt:'仅处理已授权输入，并输出符合协议的结构化结果。',promptTemplate:'',modelProfileId:type==='INPUT'?'': 'default',executionMode:type==='INPUT'?'DETERMINISTIC':'LLM',toolPermissions:[],dataPermissions:[],inputSchema:{type:'object'},outputSchema:{type:'object'},timeoutSeconds:30,maxRetries:0,required:true,failurePolicy:'STOP_RUN',costLimit:'0.100000',positionX:0,positionY:0});

export const agentFromTemplate=(template:AgentTemplateDetail):Agent=>({
  ...blankAgent(template.agentType), agentTemplateId:template.templateId, agentTemplateVersion:template.templateVersion,
  name:template.name, role:template.defaultRole, systemPrompt:template.defaultSystemPrompt,
  promptTemplate:template.defaultPromptTemplate, toolPermissions:template.supportedTools,
  inputSchema:template.inputSchema, outputSchema:template.outputSchema,
});
